### ISSUE TITLE
Delete display bug

### ISSUE THREAD

**Issue by khooroko** [CS2103AUG2017-T10-B3/main#78] opened 2017-11-03 07:13 UTC
Deleting when only one person is displayed in the list (such as `find alex` followed by `delete 1`) will cause the person list panel to turn white.

**Comment by AceCentury** [comment] 2017-11-03 07:32
Thanks for letting us know about this. We were actually aware about this issue. However, this bug seems apparent in the base version of the address book. We'll fix it if time permits.

**Comment by yuheng222** [comment] 2017-11-05 11:59
Thanks for the suggestion. Yup it is a known issue and I will try to fix it on my end.

**Comment by yuheng222** [comment] 2017-11-09 12:29
The issue is fixed as of latest [merge](https://github.com/CS2103AUG2017-T10-B3/main/pull/97) via a small modification.

**Closed as completed** 2017-11-09 12:30 UTC
